return {
  "williamboman/mason-lspconfig.nvim",
  opts = {
    automatic_installation = true,
    ensure_installed = {
      "cssls",
      "html",
      "marksman",
      "jsonls",
      "pyright",
      "tsserver",
      "yamlls",
      "bashls",
      "dockerls",
      "dotls",
      "prismals",
      "tailwindcss",
      "sqlls",
      "volar",
      "lua_ls",
      "docker_compose_language_service",
      "yamlls",
    },
  },
}
